version: '3.9'

services:
  shennong:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.4
    volumes:
      - ./data/crop.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=crop
